### PR TITLE
Add code coverage

### PR DESCRIPTION
**Pull request by dan-l**
@pdehaan Added basic code coverage reports with istanbul and instructions in README for #23

### CODE REVIEW

**Comment by pdehaan** [comment]
Current output:

```
=============================================================================
Writing coverage object [/home/travis/build/mozilla/fathom/coverage/coverage.json]
Writing coverage reports at [/home/travis/build/mozilla/fathom/coverage]
=============================================================================
=============================== Coverage summary ===============================
Statements   : 96.15% ( 225/234 )
Branches     : 86.42% ( 70/81 )
Functions    : 95% ( 38/40 )
Lines        : 96.4% ( 214/222 )
================================================================================
```

**Comment by erikrose** [comment]
Heh, those are actually pretty impressive numbers, given that I knew we had holes.

**Comment by erikrose** [comment]
Looks really good. I like that you hung it off `npm test`, which runs the slow stuff like eslint, maintaining `make test` as a quick just-the-tests-ma'am utility.

**Comment by erikrose** [comment]
Ah, found one problem: running `npm test` twice runs the linter over the coverage output (like `coverage/lcov-report/sorter.js`), and it throws a bunch of errors. Can you tell the linter to ignore those?

Before I noticed that, I was all set to merge with a couple of "polish" commits of my own layered on top: https://github.com/mozilla/fathom/compare/master...erikrose:dan-l-code-coverage?expand=1. Feel free to cherry-pick those onto your own branch, and it'll make merging simpler.

**Comment by dan-l** [comment]
You're right, missed that! Will update the PR with your commits as well.

**Comment by erikrose** [comment]
Brilliant. Thanks, @dan-l! If you or @pdehaan feel like adding a "shame badge" to the readme with the by-statement percentage, feel free.

**Comment by pdehaan** [comment]
I found some instructions at http://maximilianschmitt.me/posts/istanbul-code-coverage-badge-github/ but I don't seem to be able to find that repo in my coveralls account (but I do see about 1200 other mozilla repos). So somebody with higher powers than I may need to set that up (or find better instructions).

**Comment by dan-l** [comment]
@pdehaan  Could this be of interest?  https://github.com/lemurheavy/coveralls-public/issues/199  

Alternative: https://www.npmjs.com/package/istanbul-cobertura-badger

**Comment by erikrose** [comment]
@pdehaan I've made you a repo Admin, so give it another try. I think coveralls is probably the way to go; I've seen it widely used, and it seems straightforward.

**Pull request merged**
