### PR TITLE
Combine Fathom commands into a single one. Close #233.

### LINKED ISSUE #233: Make fathom CLI tools 1 command
Have a top-level `fathom` command with subcommands under it for `train`, `test`, etc. This would make our tools more discoverable, because there'd be a top-level `fathom --help` or `fathom help` to call.

Example: https://github.com/mozilla/dxr/blob/master/dxr/cli/__init__.py

### PR DESCRIPTION
**Pull request by erikrose**
Shorten the first line of each subcommand's docstring, because click insists on truncating these in `fathom --help`. Tweak the rest of the docstrings so they don't become awkwardly redundant.

### CODE REVIEW

**Comment by erikrose** [comment]
This does make tab completion not work as well (e.g. `fathom-hist[TAB]`). Bad enough to give up?

**Comment by erikrose** [comment]
I was going to leave those as they were, because they're accurate as of when they were written. The links still work. It's akin to how we still refer to fathom-trainees in old version notes even though that no longer exists. Do you feel strongly about it?

**Comment by danielhertenstein** [comment]
I do not.

**Comment by erikrose** [comment]
Thanks!

**Pull request merged**
