### PR TITLE
Add coveralls badge to README

### PR DESCRIPTION
**Pull request by pdehaan**
Collect coveralls code coverage info from Travis-CI.

### CODE REVIEW

**Comment by erikrose** [comment]
lgtm if tests pass. (Merge at will.)

**Comment by erikrose** [comment]
However, what's that noisy, puzzling comment the coveralls bot just made?

**Comment by pdehaan** [comment]
> However, what's that noisy, puzzling comment the coveralls bot just made?

\*shrug\*
I just disabled a checkbox on the coveralls.io page, so I think it shouldn't add comments for future PRs. But there are a few other flags there if you want to fail builds if the coverage decreases by x% in a PR.

**Comment by erikrose** [comment]
I don't have a strong opinion about it, as long as we have a graph and can tell when it happened (which it looks like we do). If you wanted to put a big number like 10 in there, that would be fine with me. Or just leave it alone.

**Pull request merged**
